### PR TITLE
Fix postgres backupconfiguration

### PR DESCRIPTION
**Pull request by nicolaiskye**
This PR fixes an issue where Stash backup pods are being instantly killed by OPA when using the included postgres helm chart. It also bumps the `library` dependency to the latest version, fixing some import issues.

### CODE REVIEW

**Comment by nicolaiskye** [comment]
This PR resolves the issue #30

**Comment by kellenrl** [comment]
This chart update will not install correctly, see: `Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(BackupConfiguration.spec.runtimeSettings.pod): unknown field "resources" in com.appscode.stash.v1beta1.BackupConfiguration.spec.runtimeSettings.pod`.

I was able to get this to run correctly by keeping everything under the `resources:` tag under `container:`, and only move the `securityContext:` under `pod:`.

This change can be seen in PR #29.

**Comment by nicolaiskye** [comment]
[868dfc5](https://github.com/olcf/slate-helm-charts/pull/31/commits/868dfc50d503cae88e3faf9bd4a3c83d806fa032) should fix that now

**Comment by kellenrl** [comment]
looks good to me.

**Pull request merged**
